name: CI Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar dependências
      run: npm install

    - name: Recompilar SQLite para Linux
      run: npm rebuild sqlite3 --build-from-source

    - name: Rodar testes do backend
      run: npm run test:backend

    - name: Rodar testes do frontend
      run: npm run test:frontend
